image: WMF 5

version: 1.0.{build}

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /update(?:|d|s) readme\..*/

environment:
  PSGalleryApiKey:
    secure: Xpt1sogACnm41S2/1LmhjIl1zn/s1u1dcwNdhLcUh8RA8eOSGaMGB8Ce8B5svBzg
  CODECOV_TOKEN:
    secure: 8XE8s/9uWz4uHhsvBGQIiVG4NUpEa80Czhfk4X6NPjwCwyx0AQHs/8Mbm5T5uTzG



install:
# Bootstrap PSDepend and Install Dependencies
- ps: |
    Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force
    Install-Module -Name PSDepend -Scope CurrentUser -Force
    Import-Module -Name PSDepend
    Invoke-PSDepend '.\REQUIREMENTS.psd1' -Force



build_script:
- ps: Invoke-psake '.\.scripts\build.ps1' -Properties @{'SkipBootStrap' = $true}



# deploy:
#   release: v$(APPVEYOR_BUILD_VERSION)
#   description: QuserObject v$(appveyor_build_version)
#   provider: GitHub
#   auth_token:
#     secure: Vw4SeFATUV5sFO3gPVSe4PRu8gtUqDxSYUHRfpH+Y2n4U65IKkcFyK1dN+j3ZQq0
#   artifact: /.*\.zip/
#   draft: false
#   prerelease: true
#   on:
#     branch: master                 # release from master branch only
#     APPVEYOR_REPO_TAG: true        # deploy except on tag push only



on_success:
# If build was started by pushed tag; deploy it.
- ps: |
    Write-Host "[AppVeyor] On Success; deploying ..." -Foregroundcolor Green
    Invoke-PSDeploy -Path '.\.scripts\deploy.ps1' -Force
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy except on tag push only
  branches:
    only:
    - master
